//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmineUpdateMain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RedmineClientMFStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RedmineClientMFStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedmineUpdateMain.RedmineClientMFStrings", typeof(RedmineClientMFStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New issue has been added: {0}.
        /// </summary>
        internal static string MFAddedIssue {
            get {
                return ResourceManager.GetString("MFAddedIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New changes in Description: {0}.
        /// </summary>
        internal static string MFCDisc {
            get {
                return ResourceManager.GetString("MFCDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New changes in Issue {0}.
        /// </summary>
        internal static string MFChangesinIssue {
            get {
                return ResourceManager.GetString("MFChangesinIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New changes in {0}.
        /// </summary>
        internal static string MFChangesinProj {
            get {
                return ResourceManager.GetString("MFChangesinProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t log in. Check whether your account is confirmed or host is available..
        /// </summary>
        internal static string MFConnError {
            get {
                return ResourceManager.GetString("MFConnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority has been changed from {0} to {1}.
        /// </summary>
        internal static string MFCPrior {
            get {
                return ResourceManager.GetString("MFCPrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done Ratio has been changed from {0}% to {1}%.
        /// </summary>
        internal static string MFCRatio {
            get {
                return ResourceManager.GetString("MFCRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status has been changed from {0} to {1}.
        /// </summary>
        internal static string MFCStat {
            get {
                return ResourceManager.GetString("MFCStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject has been changed from: {0} to {1}.
        /// </summary>
        internal static string MFCSubj {
            get {
                return ResourceManager.GetString("MFCSubj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker has been changed from {0} to {1}.
        /// </summary>
        internal static string MFCTrck {
            get {
                return ResourceManager.GetString("MFCTrck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Issue.
        /// </summary>
        internal static string MFDoI {
            get {
                return ResourceManager.GetString("MFDoI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in as {0} {1}.
        /// </summary>
        internal static string MFLogInfo {
            get {
                return ResourceManager.GetString("MFLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Issues.
        /// </summary>
        internal static string MFLoI {
            get {
                return ResourceManager.GetString("MFLoI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Projects.
        /// </summary>
        internal static string MFProjects {
            get {
                return ResourceManager.GetString("MFProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Updates.
        /// </summary>
        internal static string MFRecents {
            get {
                return ResourceManager.GetString("MFRecents", resourceCulture);
            }
        }
    }
}
